Add filter to add date to repeat post title - for HM Updates site
humanmade/apollo pull request #30
Opened 2017-12-22 11:35 UTC by dashaluna

review & merge please :)

2017-12-24 09:04 UTC, Kenshino requested changes

2017-12-24 09:04 UTC, Kenshino commented on functions.php
> +		$next_post['post_title'] .= date( $format, strtotime( $next_post['post_date'] ) );
Use date_i8ln() instead - https://developer.wordpress.org/reference/functions/date_i18n/

2017-12-25 00:22 UTC, rmccue commented on functions.php
> +		$next_post['post_title'] .= date( $format, strtotime( $next_post['post_date'] ) );
`date_i18n` isn't needed for this, given all of our sites are in English.

2017-12-25 17:11 UTC, Kenshino commented on functions.php
> +		$next_post['post_title'] .= date( $format, strtotime( $next_post['post_date'] ) );
Was looking at this as a public repo rather than just as our theme :) But happy to approve as it doesn't look like a blocker either way.

2017-12-25 17:11 UTC, merged

2017-12-28 11:26 UTC, dashaluna commented on functions.php
> +		$next_post['post_title'] .= date( $format, strtotime( $next_post['post_date'] ) );
👍